In [1]:
!pip install numpy

In [4]:
import numpy as np
arreglo=np.array([1,2,3,4])
print(arreglo)

[1 2 3 4]


In [5]:
print("El numero de dimensiones del arreglo es:", arreglo.ndim)

El numero de dimensiones del arreglo es: 1


In [7]:
import numpy as np
arreglo = np.array([1,2,3,4], dtype=float)
print(arreglo)

[1. 2. 3. 4.]


In [10]:
print("El numero de dimensiones del arrglo es:", arreglo.ndim)
print("La forma del arreglo es:", arreglo.shape)
print("El total de elementos en el arreglo es:", arreglo.size)
print("Los tipos de arreglos son:", arreglo.dtype)

El numero de dimensiones del arrglo es: 1
La forma del arreglo es: (4,)
El total de elementos en el arreglo es: 4
Los tipos de arreglos son: float64


In [13]:
arreglo_2d = np.array([[1,2,3],[4,5,6]],dtype=float)
print(arreglo_2d)

[[1. 2. 3.]
 [4. 5. 6.]]


In [14]:
print("El numero de dimensiones del arrglo es:", arreglo_2d.ndim)
print("La forma del arreglo es:", arreglo_2d.shape)
print("El total de elementos en el arreglo es:", arreglo_2d.size)
print("Los tipos de arreglos son:", arreglo_2d.dtype)

El numero de dimensiones del arrglo es: 2
La forma del arreglo es: (2, 3)
El total de elementos en el arreglo es: 6
Los tipos de arreglos son: float64


In [15]:
arreglo_3d= np.array([
    [[1,2,3],[4,5,6]],
    [[7,8,9],[10,11,12]]
])
arreglo_3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [16]:
print("El numero de dimensiones del arrglo es:", arreglo_3d.ndim)
print("La forma del arreglo es:", arreglo_3d.shape)
print("El total de elementos en el arreglo es:", arreglo_3d.size)
print("Los tipos de arreglos son:", arreglo_3d.dtype)

El numero de dimensiones del arrglo es: 3
La forma del arreglo es: (2, 2, 3)
El total de elementos en el arreglo es: 12
Los tipos de arreglos son: int64


In [18]:
ceros= np.zeros((2,3))
ceros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [19]:
unos=np.ones((4,3))
unos

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [21]:
vacio= np.empty((6,5))
vacio

array([[3.27881331e-315, 0.00000000e+000, 0.00000000e+000,
        2.22727823e-133, 5.53739487e-317],
       [3.61979475e-162, 0.00000000e+000, 0.00000000e+000,
        6.61521983e-287, 8.44852254e-322],
       [1.25162318e-308, 1.92371993e-305, 2.09119527e-085,
        1.25162314e-308, 1.37141563e-080],
       [1.25162314e-308, 8.98770952e-076, 1.25162314e-308,
        2.69469325e-109, 1.25162355e-308],
       [1.25162314e-308, 3.86019186e-066, 2.52981535e-061,
        5.62493738e-320, 0.00000000e+000],
       [2.42092166e-322, 3.27784667e-315, 6.72416037e-310,
        0.00000000e+000, 0.00000000e+000]])

In [22]:
np.arange(0,10,2)


array([0, 2, 4, 6, 8])

In [23]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [25]:
np.random.rand(2,3,1)

array([[[0.41920071],
        [0.8859083 ],
        [0.68863253]],

       [[0.19726033],
        [0.18400873],
        [0.48172126]]])

In [27]:
arreglo1= np.array([[1,0],[-1,1]])
print(arreglo1)

[[ 1  0]
 [-1  1]]


In [28]:
arreglo1/0

/tmp/ipykernel_20311/1689033109.py:1: RuntimeWarning: divide by zero encountered in divide
  arreglo1/0
/tmp/ipykernel_20311/1689033109.py:1: RuntimeWarning: invalid value encountered in divide
  arreglo1/0


array([[ inf,  nan],
       [-inf,  inf]])

In [30]:
arreglo2= np.array([[np.inf, np.nan],[1,2]])
arreglo2

array([[inf, nan],
       [ 1.,  2.]])

In [32]:
array_inf= np.array([1,2.5])**5233
print(array_inf)

[ 1. inf]


/tmp/ipykernel_20311/4189121736.py:1: RuntimeWarning: overflow encountered in power
  array_inf= np.array([1,2.5])**5233
